name: lint
on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "1.4.2"
      - name: poetry install
        run: poetry install
      - name: black
        run: poetry run black --check --verbose mdpd/ tests/
      - name: ruff
        run: poetry run ruff check --exit-non-zero-on-fix mdpd/ tests/
      - name: isort
        run: poetry run isort --check-only mdpd/ tests/
      - name: pytest
        run: poetry run pytest --doctest-modules
